apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-volume-pod
spec:
  containers:
  - name: web-server
    image: nginx:alpine
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
  volumes:
    - name: html
      gitRepo:
        repository: https://github.com/luksa/kubia-website-example.git 
        revision: master
        directory: .