apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx:alpine
      name: web-server
      volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: config
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: nginx-config

