apiVersion: v1
kind: Pod
metadata:
  name: hello-env
spec:
  containers:
    - image: 080196/hello-kube
      name: hello-env
      ports:
        - containerPort: 3000
          protocol: TCP
      env:
        - name: PORT
          value: "3000"