version: "3.5"

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: thong2303
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: mysql
    ports:
      - "3307:3306"
    volumes:
      - "./data:/var/lib/mysql"
