version: "2.1"
services:
  db:
    image: mysql:8.0
    container_name: mysql-server
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=thong2303
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    depends_on:
      - db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
