apiVersion: v1
kind: Pod
metadata: 
  name: pod-with-readness-check
spec:
  containers:
    - image: k8spatterns/random-generator:1.0
      name: random-generator
      readinessProbe:
        exec:
          command: ["stat", "/var/run/random-generator-ready"]

